packages:
  - "."
overrides:
  "@nuxt-tmpl/nuxt": "0.2.4"
  "@nuxt-tmpl/core": "0.2.1"
  "@ipa-vue/core": "0.3.5"
  "@ipa-vue/element-plus": "0.3.6"
allowBuilds:
  "@clerk/shared": true
  "@parcel/watcher": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - vue-router@5.1.0
  - "@nuxt-tmpl/*"
  - "@ipa-vue/*"
  - "@ipa-schema/*"
